### ISSUE TITLE
Outdated README / Request for new release

### ISSUE THREAD

**Issue by cpu** [Jerome1337/gofmt-action#5]
Hi there,

Is it possible that the update in https://github.com/Jerome1337/gofmt-action/pull/4 to add `gofmt-flags` also required a new version of this action be published for the README example to be usable?

When I follow [the example usage](https://github.com/microhod/gofmt-action/blob/1ab37ae9bc0737687784324fd7f414b1fef30d47/README.md#example-usage) I'm seeing a warning from Github that the `gofmt-flags` input isn't expected:

```
Warning: Unexpected input(s) 'gofmt-flags', valid inputs are ['entryPoint', 'args', 'gofmt-path']
```

Here's my `.github/workflows/gofmt.yml` workflow file:

```yaml
name: Gofmt
on: [push, pull_request]
jobs:

  build:
    name: Gofmt check
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Check gofmt
      uses: Jerome1337/gofmt-action@v1.0.2
      with:
        gofmt-path: './'
        gofmt-flags: '-l -s'
```

The README's example `uses` the `gofmt-action@v1.0.2` release but the newest published version is [v1.0.3](https://github.com/Jerome1337/gofmt-action/releases/tag/v1.0.3), unfortunately while newer than v1.0.2 I believe this tag is also missing the `gofmt-flags` commit.

Could I trouble you to publish a new release tag? I can update the README example afterwards if you like.

Thanks!
